<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="inlen8520040228" failures="2" tests="9" name="Test" time="0.19" errors="0" timestamp="2024-06-09T11:25:40 IST">
  <testcase classname="RetryLogicDemo.Example_1" name="testcase1" time="0.055">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase classname="RetryLogicDemo.Example_1" name="testcase1" time="0.002">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase classname="RetryLogicDemo.Example_1" name="testcase1" time="0.001">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase classname="RetryLogicDemo.Example_1" name="testcase1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RetryLogicDemo.Example_1.testcase1(Example_1.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testcase1 -->
  <testcase classname="RetryLogicDemo.Example_1" name="testcase2" time="0.001">
    <skipped/>
  </testcase> <!-- testcase2 -->
  <testcase classname="RetryLogicDemo.Example_1" name="testcase2" time="0.001">
    <skipped/>
  </testcase> <!-- testcase2 -->
  <testcase classname="RetryLogicDemo.Example_1" name="testcase2" time="0.001">
    <skipped/>
  </testcase> <!-- testcase2 -->
  <testcase classname="RetryLogicDemo.Example_1" name="testcase2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RetryLogicDemo.Example_1.testcase2(Example_1.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testcase2 -->
  <testcase classname="RetryLogicDemo.Example_1" name="testcase3" time="0.001"/>
</testsuite> <!-- Test -->
